### ISSUE TITLE
Email subscription error

### ISSUE THREAD

**Issue by guylepage3** [alexreardon/domevents-feedback#12]
**Describe the bug**
I received a server error when attempting to subscribe to your email updates. 

**To Reproduce**
1. Go to https://domevents.dev/
2. Enter email address in the subscribe to updates field at the bottom of the page.
3. See error below...

```
An server error occurred. We should have been notified, but you are also welcome to raise an issue on our [support project](https://github.com/alexreardon/domevents-feedback)
```

<img width="349" alt="image" src="https://github.com/alexreardon/domevents-feedback/assets/1711854/21535b71-be56-4170-b36a-932fbec3d322">

**Comment by alexreardon** [comment]
Thank you for letting me know! I'll take a look

**Comment by alexreardon** [comment]
Thank you for raising this @guylepage3. The issue has now been fixed
