### ISSUE TITLE
Typo in `cancelable` option description

### ISSUE THREAD

**Issue by Doesntmeananything** [alexreardon/domevents-feedback#6]
**Describe the bug**
There's a typo in the `Event options` `cancelable` bullet point, located in the legend.

**To Reproduce**
1. In the legend menu, go to the `Event options` submenu.
2. Observe the type in the `cancelable` bullet point:
![image](https://user-images.githubusercontent.com/34657799/118607103-e0ea7e00-b7c0-11eb-8c98-5e59fb3491d5.png)

**Comment by alexreardon** [comment]
Thanks for raising this! It is has been fixed

<img width="229" alt="Screen Shot 2021-05-18 at 6 30 41 pm" src="https://user-images.githubusercontent.com/2182637/118618646-2e89d980-b807-11eb-9975-76725fc60a26.png">
