### ISSUE TITLE
UI shifts when the left bottom menu (LEGEND) is opened

### ISSUE THREAD

**Issue by AMBudnik** [alexreardon/domevents-feedback#8]
**Describe the bug**
UI shifts when the left bottom menu (LEGEND) is opened.
The line that shows the path between elements does not shift with the UI.

**To Reproduce**
1. Click DISPATCH to draw the line between elements
2. Click any of the options from the LEGEND

**Result**
![shift](https://user-images.githubusercontent.com/10757813/118974666-5c8c2c80-b973-11eb-9ac7-3cbc846be049.gif)

**Comment by alexreardon** [comment]
Hi @AMBudnik, I think you will find this is because the browser is adding a scrollbar when a legend panel is expanded as it is usually the first time when the content is larger than the viewport

**Comment by alexreardon** [comment]
Please reopen if you think there is still an issue
